package com.pel2.ecmt.constants;

public class Queries 
{
	
	
	//CREATE TABLE QUERIES - TO CREATE THE TABLES IN THE POSTGRESS
	
	public static final String CREATEEMPLOYEE = "CREATE TABLE ECMT_EMPLOYEE(EMPID INT PRIMARY KEY NOT NULL," 
		+ "NAME	TEXT  NOT NULL,STATUS 	TEXT,TENURE INT,PHONE TEXT,"
		+ "EMAIL TEXT, DOJ DATE,WORKLOC	TEXT,HOMELOC TEXT,"
		+ "CURRLOC TEXT,RMID INT,ROLEID INT,VERTID INT,ACCTID INT)";	
	
	public static final String CREATEVERTICAL = "CREATE TABLE ECMT_VERTICAL(VERTID INT PRIMARY KEY NOT NULL," 
		+	"VERTNAME TEXT NOT NULL, SPOCID INT)";
	
	public static final String CREATEACCOUNT = "CREATE TABLE ECMT_ACCOUNT(ACCTID INT PRIMARY KEY NOT NULL," 
		+ "VERTID INT,ACCTNAME TEXT NOT NULL,SPOCID INT)";
	
	public static final String CREATEROLE = "CREATE TABLE ECMT_ROLE(ROLEID INT PRIMARY KEY NOT NULL," 
			+ "ROLEDESC	TEXT)";


	//INSERT QUERIES- INSERTING DATA INTO DATABASE
		public static final String INSERTEMPLOYEE = "INSERT INTO ECMT_EMPLOYEE(EMPID,NAME,STATUS,TENURE,PHONE, EMAIL,DOJ,WORKLOC,HOMELOC,CURRLOC,"+
		"RMID,ROLEID,VERTID,ACCTID)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
		
		public static final String INSERTACCOUNT = "INSERT INTO ECMT_ACCOUNT(ACCTID,VERTID,ACCTNAME,SPOCID) VALUES (?,?,?,?)";
		
		public static final String INSERTVERTICAL = "INSERT INTO ECMT_VERTICAL(VERTUD,VERTNAME,SPOCID) VALUES (?,?,?)";
	    
	    public static final String INSERTROLE = "INSERT INTO ECMT_ROLE(ROLEID,ROLEDESC) VALUES(?,?)";
	
	
	
	
}